/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.downloadsharedlibrary;

import android.util.Log;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.HashSet;
import java.util.Set;

public class cryptoJNI {

    cryptoJNI(String path) {
        try {
            System.load(path);
            System.loadLibrary("mytest");

            Set<String> libs = new HashSet<>();
            String mapsFile = "/proc/" + android.os.Process.myPid() + "/maps";
            BufferedReader reader = new BufferedReader(new FileReader(mapsFile));
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.endsWith(".so")) {
                    int n = line.lastIndexOf(" ");
                    libs.add(line.substring(n + 1));
                }
            }
            Log.e("TAG", libs.size() + " libraries:");
            for (String lib : libs) {
                Log.e("TAG", lib);
            }
        } catch (Exception e) {
            e.printStackTrace();
            Log.e("TAG", " Error: " + e.getMessage());
        }
    }

    public native long OpenSSL_version_num();

    public native String OpenSSL_version(int jarg1);
}
